# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import grpc.experimental

from server.pb import monitor_pb2 as monitor__pb2


class MonitoringServiceStub:
    """Client stub du service MonitoringService."""

    def __init__(self, channel):
        self.StreamMetrics = channel.unary_stream(
            "/monitor.MonitoringService/StreamMetrics",
            request_serializer=monitor__pb2.StreamRequest.SerializeToString,
            response_deserializer=monitor__pb2.MetricReport.FromString,
            _registered_method=True,
        )


class MonitoringServiceServicer:
    """Interface à implémenter côté serveur."""

    def StreamMetrics(self, request, context):
        """Flux de métriques envoyées par l'agent au serveur."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MonitoringServiceServicer_to_server(servicer, server):
    from grpc import unary_stream_rpc_method_handler as _wrap

    rpc_method_handlers = {
        "StreamMetrics": _wrap(
            servicer.StreamMetrics,
            request_deserializer=monitor__pb2.StreamRequest.FromString,
            response_serializer=monitor__pb2.MetricReport.SerializeToString,
        ),
    }
    generic_handler = grpc.method_service_handler(
        "monitor.MonitoringService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "monitor.MonitoringService", rpc_method_handlers
    )


class MonitoringService:
    """Classe utilitaire pour les tests et l'expérimentation."""

    @staticmethod
    def StreamMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/monitor.MonitoringService/StreamMetrics",
            monitor__pb2.StreamRequest.SerializeToString,
            monitor__pb2.MetricReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
