# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 0, "", "monitor.proto"
)

_sym_db = _symbol_database.Default()

from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().Add(
    b'\n\rmonitor.proto\x12\x07monitor\x1a\x1fgoogle/protobuf/timestamp.proto'
    b'\"\x9b\x01\n\x0cMetricReport\x12\x0f\n\x07node_id\x18\x01 \x01(\t'
    b'\x12\x11\n\tcpu_usage\x18\x02 \x01(\x02\x12\x11\n\tram_usage\x18\x03'
    b' \x01(\x02\x12\x12\n\ndisk_usage\x18\x04 \x01(\x02\x12.\n\ttimestamp'
    b'\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ttimestamp\"J'
    b'\n\rStreamRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x19\n'
    b'\x10interval_seconds\x18\x02 \x01(\rR\x10intervalSeconds2V\n'
    b'\x11MonitoringService\x12A\n\rStreamMetrics\x12\x16.monitor.StreamR'
    b'equest\x1a\x15.monitor.MetricReport(\x00\x30\x01B\x1e\n\x1cgithub.'
    b'com/cloudvigil/agent/pb;pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumTypes(_globals, DESCRIPTOR)
_builder.BuildTopDescriptorsAndMessages(_globals, "monitor_pb2", _globals)

if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\x1cgithub.com/cloudvigil/agent/pb;pb"

_globals["_METRICREPORT"]._serialized_start = 63
_globals["_METRICREPORT"]._serialized_end = 218
_globals["_STREAMREQUEST"]._serialized_start = 220
_globals["_STREAMREQUEST"]._serialized_end = 294
