// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl   "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect     "reflect"
	sync        "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricReport contient les métriques système collectées par un agent.
type MetricReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsage  float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage  float32                `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	DiskUsage float32                `protobuf:"fixed32,4,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *MetricReport) Reset()         { *x = MetricReport{} }
func (x *MetricReport) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *MetricReport) ProtoMessage()  {}

func (x *MetricReport) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetricReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetricReport) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricReport) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *MetricReport) GetDiskUsage() float32 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *MetricReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// StreamRequest est envoyé par l'agent pour initier le flux.
type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId          string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IntervalSeconds uint32 `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
}

func (x *StreamRequest) Reset()         { *x = StreamRequest{} }
func (x *StreamRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *StreamRequest) ProtoMessage()  {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StreamRequest) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

var file_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)

var File_monitor_proto protoreflect.FileDescriptor
