// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl   "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricReport contient les métriques système collectées par un agent.
type MetricReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsage  float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage  float32                `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	DiskUsage float32                `protobuf:"fixed32,4,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *MetricReport) Reset()         { *x = MetricReport{} }
func (x *MetricReport) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *MetricReport) ProtoMessage()  {}

func (x *MetricReport) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetricReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MetricReport) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricReport) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *MetricReport) GetDiskUsage() float32 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *MetricReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// StreamRequest est envoyé par l'agent pour initier le flux.
type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId          string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IntervalSeconds uint32 `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
}

func (x *StreamRequest) Reset()         { *x = StreamRequest{} }
func (x *StreamRequest) String() string  { return protoimpl.X.MessageStringOf(x) }
func (x *StreamRequest) ProtoMessage()  {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StreamRequest) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

// ContainerInfo représente l'état et la consommation de ressources d'un conteneur Docker.
type ContainerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image      string  `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	State      string  `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CpuPercent float32 `protobuf:"fixed32,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsageMb float32 `protobuf:"fixed32,6,opt,name=mem_usage_mb,json=memUsageMb,proto3" json:"mem_usage_mb,omitempty"`
	MemLimitMb float32 `protobuf:"fixed32,7,opt,name=mem_limit_mb,json=memLimitMb,proto3" json:"mem_limit_mb,omitempty"`
}

func (x *ContainerInfo) Reset()        { *x = ContainerInfo{} }
func (x *ContainerInfo) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerInfo) GetId() string         { if x != nil { return x.Id }; return "" }
func (x *ContainerInfo) GetName() string        { if x != nil { return x.Name }; return "" }
func (x *ContainerInfo) GetImage() string       { if x != nil { return x.Image }; return "" }
func (x *ContainerInfo) GetState() string       { if x != nil { return x.State }; return "" }
func (x *ContainerInfo) GetCpuPercent() float32 { if x != nil { return x.CpuPercent }; return 0 }
func (x *ContainerInfo) GetMemUsageMb() float32 { if x != nil { return x.MemUsageMb }; return 0 }
func (x *ContainerInfo) GetMemLimitMb() float32 { if x != nil { return x.MemLimitMb }; return 0 }

// DockerReport contient le snapshot Docker d'un nœud à un instant donné.
type DockerReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId     string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Containers []*ContainerInfo       `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *DockerReport) Reset()        { *x = DockerReport{} }
func (x *DockerReport) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DockerReport) ProtoMessage() {}

func (x *DockerReport) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DockerReport) GetNodeId() string               { if x != nil { return x.NodeId }; return "" }
func (x *DockerReport) GetContainers() []*ContainerInfo { if x != nil { return x.Containers }; return nil }
func (x *DockerReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// StreamResponse est renvoyé par le serveur à la clôture du flux.
type StreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StreamResponse) Reset()        { *x = StreamResponse{} }
func (x *StreamResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var file_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)

var File_monitor_proto protoreflect.FileDescriptor
