// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: monitor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitoringService_StreamMetrics_FullMethodName      = "/monitor.MonitoringService/StreamMetrics"
	MonitoringService_StreamDockerStatus_FullMethodName = "/monitor.MonitoringService/StreamDockerStatus"
)

// MonitoringServiceClient is the client API for MonitoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MonitoringService expose les méthodes de collecte de métriques en temps réel.
type MonitoringServiceClient interface {
	// StreamMetrics : flux système (CPU / RAM / disque).
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricReport, StreamResponse], error)
	// StreamDockerStatus : flux Docker — l'agent envoie l'état des conteneurs si Docker est détecté.
	StreamDockerStatus(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DockerReport, StreamResponse], error)
}

type monitoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringServiceClient(cc grpc.ClientConnInterface) MonitoringServiceClient {
	return &monitoringServiceClient{cc}
}

func (c *monitoringServiceClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricReport, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitoringService_ServiceDesc.Streams[0], MonitoringService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricReport, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoringService_StreamMetricsClient = grpc.ClientStreamingClient[MetricReport, StreamResponse]

func (c *monitoringServiceClient) StreamDockerStatus(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DockerReport, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitoringService_ServiceDesc.Streams[1], MonitoringService_StreamDockerStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DockerReport, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoringService_StreamDockerStatusClient = grpc.ClientStreamingClient[DockerReport, StreamResponse]

// MonitoringServiceServer is the server API for MonitoringService service.
// All implementations must embed UnimplementedMonitoringServiceServer
// for forward compatibility.
//
// MonitoringService expose les méthodes de collecte de métriques en temps réel.
type MonitoringServiceServer interface {
	// StreamMetrics : flux système (CPU / RAM / disque).
	StreamMetrics(grpc.ClientStreamingServer[MetricReport, StreamResponse]) error
	// StreamDockerStatus : flux Docker — l'agent envoie l'état des conteneurs si Docker est détecté.
	StreamDockerStatus(grpc.ClientStreamingServer[DockerReport, StreamResponse]) error
	mustEmbedUnimplementedMonitoringServiceServer()
}

// UnimplementedMonitoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitoringServiceServer struct{}

func (UnimplementedMonitoringServiceServer) StreamMetrics(grpc.ClientStreamingServer[MetricReport, StreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedMonitoringServiceServer) StreamDockerStatus(grpc.ClientStreamingServer[DockerReport, StreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDockerStatus not implemented")
}
func (UnimplementedMonitoringServiceServer) mustEmbedUnimplementedMonitoringServiceServer() {}
func (UnimplementedMonitoringServiceServer) testEmbeddedByValue()                           {}

// UnsafeMonitoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoringServiceServer will
// result in compilation errors.
type UnsafeMonitoringServiceServer interface {
	mustEmbedUnimplementedMonitoringServiceServer()
}

func RegisterMonitoringServiceServer(s grpc.ServiceRegistrar, srv MonitoringServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitoringService_ServiceDesc, srv)
}

func _MonitoringService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitoringServiceServer).StreamMetrics(&grpc.GenericServerStream[MetricReport, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoringService_StreamMetricsServer = grpc.ClientStreamingServer[MetricReport, StreamResponse]

func _MonitoringService_StreamDockerStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitoringServiceServer).StreamDockerStatus(&grpc.GenericServerStream[DockerReport, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoringService_StreamDockerStatusServer = grpc.ClientStreamingServer[DockerReport, StreamResponse]

// MonitoringService_ServiceDesc is the grpc.ServiceDesc for MonitoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.MonitoringService",
	HandlerType: (*MonitoringServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _MonitoringService_StreamMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamDockerStatus",
			Handler:       _MonitoringService_StreamDockerStatus_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "monitor.proto",
}
