// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: monitor.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ── Client ────────────────────────────────────────────────────────────────────

// MonitoringServiceClient est l'interface client du service gRPC.
type MonitoringServiceClient interface {
	// StreamMetrics : flux système (CPU / RAM / disque).
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (MonitoringService_StreamMetricsClient, error)
	// StreamDockerStatus : flux Docker — liste des conteneurs et leurs ressources.
	StreamDockerStatus(ctx context.Context, opts ...grpc.CallOption) (MonitoringService_StreamDockerStatusClient, error)
}

type monitoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringServiceClient(cc grpc.ClientConnInterface) MonitoringServiceClient {
	return &monitoringServiceClient{cc}
}

func (c *monitoringServiceClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (MonitoringService_StreamMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MonitoringService_ServiceDesc.Streams[0], "/monitor.MonitoringService/StreamMetrics", opts...)
	if err != nil {
		return nil, err
	}
	return &monitoringServiceStreamMetricsClient{stream}, nil
}

type MonitoringService_StreamMetricsClient interface {
	Send(*MetricReport) error
	CloseAndRecv() (*StreamResponse, error)
	grpc.ClientStream
}

type monitoringServiceStreamMetricsClient struct {
	grpc.ClientStream
}

func (x *monitoringServiceStreamMetricsClient) Send(m *MetricReport) error {
	return x.ClientStream.SendMsg(m)
}

func (x *monitoringServiceStreamMetricsClient) CloseAndRecv() (*StreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *monitoringServiceClient) StreamDockerStatus(ctx context.Context, opts ...grpc.CallOption) (MonitoringService_StreamDockerStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &MonitoringService_ServiceDesc.Streams[1], "/monitor.MonitoringService/StreamDockerStatus", opts...)
	if err != nil {
		return nil, err
	}
	return &monitoringServiceStreamDockerStatusClient{stream}, nil
}

type MonitoringService_StreamDockerStatusClient interface {
	Send(*DockerReport) error
	CloseAndRecv() (*StreamResponse, error)
	grpc.ClientStream
}

type monitoringServiceStreamDockerStatusClient struct {
	grpc.ClientStream
}

func (x *monitoringServiceStreamDockerStatusClient) Send(m *DockerReport) error {
	return x.ClientStream.SendMsg(m)
}

func (x *monitoringServiceStreamDockerStatusClient) CloseAndRecv() (*StreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ── Serveur ───────────────────────────────────────────────────────────────────

// MonitoringServiceServer est l'interface à implémenter côté serveur.
type MonitoringServiceServer interface {
	StreamMetrics(MonitoringService_StreamMetricsServer) error
	StreamDockerStatus(MonitoringService_StreamDockerStatusServer) error
	mustEmbedUnimplementedMonitoringServiceServer()
}

// UnimplementedMonitoringServiceServer doit être embarqué pour la compatibilité future.
type UnimplementedMonitoringServiceServer struct{}

func (UnimplementedMonitoringServiceServer) StreamMetrics(MonitoringService_StreamMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}

func (UnimplementedMonitoringServiceServer) StreamDockerStatus(MonitoringService_StreamDockerStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamDockerStatus not implemented")
}

func (UnimplementedMonitoringServiceServer) mustEmbedUnimplementedMonitoringServiceServer() {}

// UnsafeMonitoringServiceServer peut être embarqué sans garantie de compatibilité ascendante.
type UnsafeMonitoringServiceServer interface {
	mustEmbedUnimplementedMonitoringServiceServer()
}

func RegisterMonitoringServiceServer(s grpc.ServiceRegistrar, srv MonitoringServiceServer) {
	s.RegisterService(&MonitoringService_ServiceDesc, srv)
}

type MonitoringService_StreamMetricsServer interface {
	SendAndClose(*StreamResponse) error
	Recv() (*MetricReport, error)
	grpc.ServerStream
}

type monitoringServiceStreamMetricsServer struct {
	grpc.ServerStream
}

func (x *monitoringServiceStreamMetricsServer) SendAndClose(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *monitoringServiceStreamMetricsServer) Recv() (*MetricReport, error) {
	m := new(MetricReport)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitoringService_StreamDockerStatusServer — interface serveur pour StreamDockerStatus.
type MonitoringService_StreamDockerStatusServer interface {
	SendAndClose(*StreamResponse) error
	Recv() (*DockerReport, error)
	grpc.ServerStream
}

type monitoringServiceStreamDockerStatusServer struct {
	grpc.ServerStream
}

func (x *monitoringServiceStreamDockerStatusServer) SendAndClose(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *monitoringServiceStreamDockerStatusServer) Recv() (*DockerReport, error) {
	m := new(DockerReport)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ── Descripteur de service ────────────────────────────────────────────────────

var MonitoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.MonitoringService",
	HandlerType: (*MonitoringServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _MonitoringService_StreamMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamDockerStatus",
			Handler:       _MonitoringService_StreamDockerStatus_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "monitor.proto",
}

func _MonitoringService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitoringServiceServer).StreamMetrics(&monitoringServiceStreamMetricsServer{stream})
}

func _MonitoringService_StreamDockerStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitoringServiceServer).StreamDockerStatus(&monitoringServiceStreamDockerStatusServer{stream})
}
